### ISSUE TITLE
Generating icons fails on GitHub Action's windows runner

### ISSUE THREAD

**Issue by stijnfrishert** [juce-framework/JUCE#908]
I've got a GitHub Actions windows runner that builds my JUCE project with CMake.
When building locally, everything works fine, but the GA runner bails out during CMake configuration:

```
CMake Error at deps/JUCE/extras/Build/CMake/JUCEUtils.cmake:2152 (add_executable):
  Cannot find source file:

    D:/a/tunesmith/tunesmith/build/Editor_artefacts/JuceLibraryCode/icon.ico

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc
Call Stack (most recent call first):
  CMakeLists.txt:10 (juce_add_gui_app)
```

This is my CMake function call:
```
juce_add_gui_app(Editor
    ICON_BIG "resource/image/icon.png"
    ICON_SMALL "resource/image/icon.png"
    PRODUCT_NAME "Tunesmith")
```

And this is my GitHub workflow yaml:
```
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      working-directory: ${{github.workspace}}/editor
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    ...
```

Any idea what could be causing this? What is JUCE using to generate the `.ico` file?

I've got JUCE checked out as a submodule with commit [`ffdfb5b43672aa75e911d89e2899bb48bf02cd30`](https://github.com/juce-framework/JUCE/commit/ffdfb5b43672aa75e911d89e2899bb48bf02cd30) (lastest on `development`).
